import { CityConfig, RiskWeightsConfig, WaterBody } from './types';

export const CITIES: CityConfig[] = [
  {
    id: 'chennai',
    name: 'Chennai',
    region: 'Tamil Nadu',
    country: 'India',
    lat: 13.0827,
    lon: 80.2707,
    bbox: [12.75, 80.00, 13.35, 80.35],
  },
  {
    id: 'mumbai',
    name: 'Mumbai',
    region: 'Maharashtra',
    country: 'India',
    lat: 19.0760,
    lon: 72.8777,
    bbox: [18.85, 72.75, 19.30, 73.05],
  },
  {
    id: 'goa',
    name: 'Goa Coast',
    region: 'Goa',
    country: 'India',
    lat: 15.4909,
    lon: 73.8278,
    bbox: [15.00, 73.65, 15.80, 74.15],
  },
  {
    id: 'sydney',
    name: 'Sydney',
    region: 'NSW',
    country: 'Australia',
    lat: -33.8688,
    lon: 151.2093,
    bbox: [-34.10, 151.00, -33.60, 151.40],
  },
  {
    id: 'miami',
    name: 'Miami',
    region: 'Florida',
    country: 'USA',
    lat: 25.7617,
    lon: -80.1918,
    bbox: [25.55, -80.35, 25.95, -80.05],
  },
];

export const DEFAULT_RISK_WEIGHTS: RiskWeightsConfig = {
  waveHeight: 22,
  ripCurrent: 12,
  rainfall: 14,
  windGusts: 10,
  runoffAnomaly: 8,
  severeWeather: 8,
  lowVisibility: 5,
  waterTempExtreme: 3,
  tideVariability: 5,
  exposure: 10,
  mitigation: 8,
  waveHeightWeight: 22,
  wavePeriodWeight: 12,
  windSpeedWeight: 10,
  precipitationWeight: 14,
  riverDischargeWeight: 8,
  lifeguardMitigation: 8,
};

export const RISK_TIERS = {
  LOW_MAX: 34.9,
  MED_MAX: 69.9,
  HIGH_MIN: 70.0,
  SEVERE_MIN: 85.0,
};

export const CHENNAI_SEED_SITES: WaterBody[] = [
  {
    id: 'chennai-marina',
    name: 'Marina Beach',
    type: 'beach',
    lat: 13.0500,
    lon: 80.2824,
    region: 'Chennai Central',
    isCoastal: true,
    lifeguardPresent: true,
    infrastructureIndex: 82,
    infrastructureCounts: {
      lifeguardStations: 3,
      hospitals: 5,
      police: 4,
      fireStations: 2,
      emergencyPhones: 4,
    },
    source: 'seed',
  },
  {
    id: 'chennai-elliots',
    name: "Elliot's (Besant Nagar) Beach",
    type: 'beach',
    lat: 12.9994,
    lon: 80.2707,
    region: 'Chennai South',
    isCoastal: true,
    lifeguardPresent: true,
    infrastructureIndex: 78,
    infrastructureCounts: {
      lifeguardStations: 2,
      hospitals: 4,
      police: 3,
      fireStations: 2,
      emergencyPhones: 3,
    },
    source: 'seed',
  },
  {
    id: 'chennai-thiruvanmiyur',
    name: 'Thiruvanmiyur Beach',
    type: 'beach',
    lat: 12.9830,
    lon: 80.2660,
    region: 'Chennai South',
    isCoastal: true,
    lifeguardPresent: false,
    infrastructureIndex: 58,
    infrastructureCounts: {
      lifeguardStations: 0,
      hospitals: 3,
      police: 2,
      fireStations: 1,
      emergencyPhones: 1,
    },
    source: 'seed',
  },
  {
    id: 'chennai-neelankarai',
    name: 'Neelankarai Beach',
    type: 'beach',
    lat: 12.9490,
    lon: 80.2580,
    region: 'ECR Coast',
    isCoastal: true,
    lifeguardPresent: false,
    infrastructureIndex: 44,
    infrastructureCounts: {
      lifeguardStations: 0,
      hospitals: 2,
      police: 1,
      fireStations: 1,
      emergencyPhones: 0,
    },
    source: 'seed',
  },
  {
    id: 'chennai-palavakkam',
    name: 'Palavakkam Beach',
    type: 'beach',
    lat: 12.9645,
    lon: 80.2612,
    region: 'ECR Coast',
    isCoastal: true,
    lifeguardPresent: false,
    infrastructureIndex: 46,
    infrastructureCounts: {
      lifeguardStations: 0,
      hospitals: 2,
      police: 1,
      fireStations: 1,
      emergencyPhones: 1,
    },
    source: 'seed',
  },
  {
    id: 'chennai-kovalam',
    name: 'Kovalam (Covelong) Beach',
    type: 'beach',
    lat: 12.7925,
    lon: 80.2514,
    region: 'Kanchipuram District',
    isCoastal: true,
    lifeguardPresent: true,
    infrastructureIndex: 65,
    infrastructureCounts: {
      lifeguardStations: 2,
      hospitals: 2,
      police: 2,
      fireStations: 1,
      emergencyPhones: 2,
    },
    source: 'seed',
  },
  {
    id: 'chennai-chembarambakkam',
    name: 'Chembarambakkam Lake',
    type: 'reservoir',
    lat: 13.0118,
    lon: 80.0577,
    region: 'Kanchipuram Hinterland',
    isCoastal: false,
    lifeguardPresent: false,
    infrastructureIndex: 32,
    infrastructureCounts: {
      lifeguardStations: 0,
      hospitals: 1,
      police: 1,
      fireStations: 1,
      emergencyPhones: 0,
    },
    source: 'seed',
  },
  {
    id: 'chennai-puzhal',
    name: 'Puzhal (Red Hills) Lake',
    type: 'lake',
    lat: 13.1930,
    lon: 80.1780,
    region: 'Chennai North',
    isCoastal: false,
    lifeguardPresent: false,
    infrastructureIndex: 40,
    infrastructureCounts: {
      lifeguardStations: 0,
      hospitals: 2,
      police: 1,
      fireStations: 1,
      emergencyPhones: 1,
    },
    source: 'seed',
  },
  {
    id: 'chennai-adyar',
    name: 'Adyar Estuary & River',
    type: 'river',
    lat: 13.0105,
    lon: 80.2760,
    region: 'Adyar',
    isCoastal: true,
    lifeguardPresent: false,
    infrastructureIndex: 62,
    infrastructureCounts: {
      lifeguardStations: 0,
      hospitals: 3,
      police: 3,
      fireStations: 2,
      emergencyPhones: 2,
    },
    source: 'seed',
  },
  {
    id: 'chennai-muttukadu',
    name: 'Muttukadu Backwaters',
    type: 'lake',
    lat: 12.8228,
    lon: 80.2458,
    region: 'ECR South',
    isCoastal: true,
    lifeguardPresent: true,
    infrastructureIndex: 54,
    infrastructureCounts: {
      lifeguardStations: 1,
      hospitals: 1,
      police: 2,
      fireStations: 1,
      emergencyPhones: 1,
    },
    source: 'seed',
  },
  {
    id: 'chennai-ennore',
    name: 'Ennore Creek & Estuary',
    type: 'river',
    lat: 13.2285,
    lon: 80.3235,
    region: 'Ennore / North Chennai',
    isCoastal: true,
    lifeguardPresent: false,
    infrastructureIndex: 38,
    infrastructureCounts: {
      lifeguardStations: 0,
      hospitals: 1,
      police: 2,
      fireStations: 1,
      emergencyPhones: 0,
    },
    source: 'seed',
  },
  {
    id: 'chennai-poondi',
    name: 'Poondi Reservoir',
    type: 'reservoir',
    lat: 13.1894,
    lon: 79.8601,
    region: 'Tiruvallur District',
    isCoastal: false,
    lifeguardPresent: false,
    infrastructureIndex: 26,
    infrastructureCounts: {
      lifeguardStations: 0,
      hospitals: 1,
      police: 1,
      fireStations: 0,
      emergencyPhones: 0,
    },
    source: 'seed',
  },
];

export function getEsriSatelliteThumbnail(lat: number, lon: number, delta: number = 0.015): string {
  const south = lat - delta;
  const north = lat + delta;
  const west = lon - delta * 1.33;
  const east = lon + delta * 1.33;
  const bbox = `${west},${south},${east},${north}`;
  return `https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/export?bbox=${bbox}&bboxSR=4326&imageSR=4326&size=400,300&format=jpg&f=image`;
}

export function getEsriCoastSatelliteUrl(
  bbox: [number, number, number, number],
  width: number = 2000,
  height: number = 1200,
  cityId?: string
): string {
  // If Chennai: tighter shoreline crop (about 6 km wide, harbour to Marina Beach) at 2000x1200
  if (cityId === 'chennai') {
    return `https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/export?bbox=80.255,13.030,80.315,13.105&bboxSR=4326&imageSR=4326&size=${width},${height}&format=jpg&f=image`;
  }
  const [south, west, north, east] = bbox;
  return `https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/export?bbox=${west},${south},${east},${north}&bboxSR=4326&imageSR=4326&size=${width},${height}&format=jpg&f=image`;
}


